/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { AppointmentUpdateManyWithoutDoctorsInput } from "./AppointmentUpdateManyWithoutDoctorsInput";
import { Type } from "class-transformer";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { ConversationUpdateManyWithoutDoctorsInput } from "./ConversationUpdateManyWithoutDoctorsInput";

@InputType()
class DoctorUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialization?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ConversationUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => ConversationUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => ConversationUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  conversations?: ConversationUpdateManyWithoutDoctorsInput;
}

export { DoctorUpdateInput as DoctorUpdateInput };
